[package]
name = "std-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[[bin]]
name = "std-dev"
path = "src/bin/main.rs"
required-features = ["bin"]

[dependencies]
colored = { version = "2.0", optional = true }
atty = { version = "0.2.14", optional = true }
nalgebra = { version = "0.30", optional = true }
clap = { version = "3", optional = true, features = ["cargo"] }

[features]
default = ["bin", "pretty", "regression"]

##
# Library features (also applies to binary)
##

regression = ["nalgebra"]


##
# Binary features
##

bin = ["clap"]

# Prettier bin output
pretty = ["bin", "atty", "colored"]
