[package]
name = "std-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = { version = "0.2.14", optional = true }

[features]
default = ["pretty"]

# Prettier bin output
pretty = ["atty"]
